### ISSUE TITLE
Grammatical error on homepage.

### ISSUE THREAD

**Issue by hagenhaus** [OAI/learn.openapis.org#114]
The following sentence appears on the [openapis.org](https://www.openapis.org/) homepage:

**The OpenAPI Specifications provides a formal standard for describing HTTP APIs.**

This sentence is grammatically incorrect: The subject is plural and the verb is singular.

Correct alternatives include the following:

**The OpenAPI Specifications provide a formal standard for describing HTTP APIs.**

**The OpenAPI Specification provides a formal standard for describing HTTP APIs.**

I apologize for submitting this to the [learn.openapis.org](https://learn.openapis.org/) repo. I cannot find the openapis.org repo.

Thank you.

**Comment by ralfhandl** [comment]
@hagenhaus Thanks for finding this!

If you find more, please don't hesitate to open issues. And this repo seems like a good place for issues related to the home page.

**Comment by ralfhandl** [comment]
@swaldron58 Could you please fix this?

**Comment by swaldron58** [comment]
Done, thanks!
