### ISSUE TITLE
Rename repo to "learn" or "Learn-OpenAPI"

### ISSUE THREAD

**Issue by handrews** [OAI/learn.openapis.org#68]
@MikeRalphson suggested perhaps renaming this repo on Slack yesterday, suggesting "learn" as that is the site name.  I'd suggest "Learn-OpenAPI" to make the repo name more distinctive and less likely to collide when someone forks it ("Documentation" is about as generic and collision-likely as they come).  "Learn-OpenAPI" also matches the capitalization of "OpenAPI-Specification", "Documentation", etc.

**Comment by darrelmiller** [comment]
Done.
