### ISSUE TITLE
Are issues/PRs here being reviewed?

### ISSUE THREAD

**Issue by davidleger95** [OAI/learn.openapis.org#72]
I see a few issues/PRs that have been up for months without a response. Just wondering if someone is actively maintaining this site still.

**Comment by lornajane** [comment]
Thanks for taking an interest! The project is active, some issues and pull requests have been updated recently, some have gone a bit quiet but we're all volunteers so things get done when they get done. Did you have a particular change in mind or a request for us?

**Comment by lornajane** [comment]
I'm not sure there was an actual request in this issue, so I'll close it. Please open an issue with your specific request or comment if appropriate.
